### ISSUE TITLE
[Idea] Open files automatically if editor is defined

### ISSUE THREAD

**Issue by tabacitu** [webfactor/laravel-generators#26]
## Detailed description

Right now you have to specify ```--ide=sublime``` to open the files after generation. But a hidden feature of Laravel is to specify ```config('app.editor')```. That will automatically open the files generated with ```make```: https://twitter.com/marcelpociot/status/1016784890128470017

This package could do the same, and, if ```config('app.editor')``` is present, would open them in said editor.

That being said, I don't think the Laravel implementation for this is great - I personally would have preferred an .ENV variable. But hey... that's what we've got...

**Comment by OliverZiegler** [comment]
couldn't we use both?

say checking for
* .env variable `APP_EDITOR`
* checking`config('app.editor')

but if `--ide=` is provided we overwrite what we found?

**Comment by tabacitu** [comment]
Oups. Sorry - that’s what I meant. Both :D
