### ISSUE TITLE
Small syntax change proposal

### ISSUE THREAD

**Issue by tabacitu** [webfactor/laravel-generators#37]
## Detailed description

Ok so this is another small one, but one that I found confusing at first - I said nothing 'cause I expected to get used to it. But I didn't get used to it, I still find it a bit awkward. So here goes, maybe you'll agree with me.

I _personally_ don't like the fact that the syntax asks me to separate field/column options with ```;```. That I have to type ```;``` (which both in English and all programming languages signifies a stop) to define details for something, then type ```,``` (enumeration). It feels... _wrong_ to have an enumeration of things that have full stops in it. It's like the sentence ends, but they wait, it's an enumeration so it continues.

Told you it's a small one :-)

## Context

So if I were to split a normal command by lines it would be:
```bash
php artisan make:entity king 
   --ide=0
   --migrate 
   --schema="
         first_name:string(required);rule(required|min:3|max:64);field(label: Small Name), 
         last_name:string;field(label:Family Name), 
         nickname:string(nullable), 
         age:integer, 
         bio:summernote(nullable);rule(nullable), 
         extras:text(nullable);rule(nullable)"
```

## Possible implementation

I would argue that maybe it makes more sense to use something like ```[ ]``` to define extra options:

```bash
php artisan make:entity king 
   --ide=0
   --migrate 
   --schema="
         first_name:string(required)[rule(required|min:3|max:64),field(label: Small Name)], 
         last_name:string[field(label: Family Name)], 
         nickname:string(nullable), 
         age:integer, 
         bio:summernote(nullable)[rule(nullable)], 
         extras:text(nullable)[rule(nullable)]" 
```

So basically we'd have _exactly_ the same syntax as [laracasts/Laravel-5-Generators-Extended](https://github.com/laracasts/Laravel-5-Generators-Extended) - everything you add on top of that syntax would be inside ```[ ]```. That should be a lot easier to remember, and see.

What do you think? Feel free to say I'm crazy :-)

Please mind that **I'm not sure ```[ ]``` is the best solution** - it's just the first one that popped into my head. We could also replace ```;``` with another character like ```/```, maybe ```>``` or ```%```, ```&```. Replacing with a different character would actually:
- be easier to implement
- make it easier to write, since there's no ending bracket

So alternatives:

```bash
php artisan make:entity king 
   --ide=0
   --migrate 
   --schema="
         first_name:string(required) > rule(required|min:3|max:64),field(label: Small Name), 
         last_name:string > field(label: Family Name), 
         nickname:string(nullable), 
         age:integer, 
         bio:summernote(nullable) > rule(nullable), 
         extras:text(nullable) > rule(nullable)" 
```

```bash
php artisan make:entity king 
   --ide=0
   --migrate 
   --schema="
         first_name:string(required) / rule(required|min:3|max:64), field(label: Small Name), 
         last_name:string / field(label: Family Name), 
         nickname:string(nullable), 
         age:integer, 
         bio:summernote(nullable) / rule(nullable), 
         extras:text(nullable) / rule(nullable)" 
```

We would have to find a character that is never used inside [validation rules](https://laravel.com/docs/5.7/validation#available-validation-rules), though. 

I _think_ ```>```:
- can't be used inside validations - there's ```min```, ```max```, ```before```, ```after```, ```less_than``` and ```greater_than```;
- is a common character inside command lines;
- is easy to type, because in PHP we often type ```=>```;
- does NOT signify a line stop, or a sentence stop; or a command stop;
- CAN signify "details", thanks to PHP arrays;

So I think ```>``` would be my favorite - sounds like a better choice than ```;``` or ```[ ]``` right now.

What do you think?

**Comment by tswonke** [comment]
Thank you for your thoughts, @tabacitu !

I'm not 100% happy with `;` either, but we think it's the best compromise for now:

- It's easy to type on german/english keyboards
- Parsing is easy as well

As soon as we use `,` also inside the "options" parsing will get more difficult.

One could think of using a DDL schema in the future (maybe v4), but this has to be thoroughly elaborated.

For now I will close that issue, but keep it in mind for further developments! :-)

**Comment by tabacitu** [comment]
Ok, sure!
