### ISSUE TITLE
Not compatible with Laravel 7 

### ISSUE THREAD

**Issue by brynnb** [webfactor/laravel-generators#42]
I am updating a Laravel 6 site to 7 and this was the only package I had to remove to make it work. Getting the following:

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: remove laravel/framework v7.11.0
    - Conclusion: don't install laravel/framework v7.11.0
    - Conclusion: don't install laravel/framework v7.10.3
    - Conclusion: don't install laravel/framework v7.10.2
    - Conclusion: don't install laravel/framework v7.10.1
    - Conclusion: don't install laravel/framework v7.10.0
    - Conclusion: don't install laravel/framework v7.9.2
    - Conclusion: don't install laravel/framework v7.9.1
    - Conclusion: don't install laravel/framework v7.9.0
    - Conclusion: don't install laravel/framework v7.8.1
    - Conclusion: don't install laravel/framework v7.8.0
    - Conclusion: don't install laravel/framework v7.7.1
    - Conclusion: don't install laravel/framework v7.7.0
    - Conclusion: don't install laravel/framework v7.6.2
    - Conclusion: don't install laravel/framework v7.6.1
    - Conclusion: don't install laravel/framework v7.6.0
    - Conclusion: don't install laravel/framework v7.5.2
    - Conclusion: don't install laravel/framework v7.5.1
    - Conclusion: don't install laravel/framework v7.5.0
    - Conclusion: don't install laravel/framework v7.4.0
    - Conclusion: don't install laravel/framework v7.3.0
    - Conclusion: don't install laravel/framework v7.2.2
    - Conclusion: don't install laravel/framework v7.2.1
    - Conclusion: don't install laravel/framework v7.2.0
    - Conclusion: don't install laravel/framework v7.1.3
    - Conclusion: don't install laravel/framework v7.1.2
    - Conclusion: don't install laravel/framework v7.1.1
    - Conclusion: don't install laravel/framework v7.1.0
    - Conclusion: don't install laravel/framework v7.0.8
    - Conclusion: don't install laravel/framework v7.0.7
    - Conclusion: don't install laravel/framework v7.0.6
    - Conclusion: don't install laravel/framework v7.0.5
    - Conclusion: don't install laravel/framework v7.0.4
    - Conclusion: don't install laravel/framework v7.0.3
    - Conclusion: don't install laravel/framework v7.0.2
    - Conclusion: don't install laravel/framework v7.0.1
    - Conclusion: don't install laravel/framework v7.0.0
    - webfactor/laravel-generators 3.3.0 requires illuminate/database ~5.5.0|~5.6.0|~5.7.0 -> satisfiable by laravel/framework[5.5.x-dev, 5.6.x-dev, 5.7.x-dev], illuminate/database[5.5.x-dev, 5.6.x-dev, 5.7.17, 5.7.18, 5.7.19, 5.7.x-dev, v5.5.0, v5.5.16, v5.5.17, v
5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39, v5.5.40, v5.5.41, v5.5.43, v5.5.44, v5.6.0, v5.6.1, v5.6.10, v5.6.11, v5.6.12, v5.6.13, v5.6.14, v5.6.15, v5.6.16, v5.6.17, v5.6.19, v5.6.2, v5.6.20, v5.6.21, v5.6.22, v5.6.23, v5.6.24, v5.6.25,
v5.6.26, v5.6.27, v5.6.28, v5.6.29, v5.6.3, v5.6.30, v5.6.31, v5.6.32, v5.6.33, v5.6.34, v5.6.35, v5.6.36, v5.6.37, v5.6.38, v5.6.39, v5.6.4, v5.6.5, v5.6.6, v5.6.7, v5.6.8, v5.6.9, v5.7.0, v5.7.1, v5.7.10, v5.7.11, v5.7.15, v5.7.2, v5.7.20, v5.7.21, v5.7.22, v5.7.
23, v5.7.26, v5.7.27, v5.7.28, v5.7.3, v5.7.4, v5.7.5, v5.7.6, v5.7.7, v5.7.8, v5.7.9].

**Comment by tswonke** [comment]
I added Laravel 7 to composer.json - but untested

**Comment by brynnb** [comment]
`composer require --dev webfactor/laravel-generators` now installs successfully but I have also not tested functionality. Thanks!
