### ISSUE TITLE
wrong validation rules

### ISSUE THREAD

**Issue by OliverZiegler** [webfactor/laravel-generators#8]
It seems like there is a typo in the validator generation.

The applied rule `require` does not exist. This should be `required`.

Also it seems like `nullable` fields get also the rule `required` which seems like a bug ;)

**Comment by tswonke** [comment]
You may create a pull request, Oli! 😁
I will soon proceed with v3

**Comment by OliverZiegler** [comment]
@tswonke when I got time ;)

Just adding my findings here so we don't forget them ;)

**Comment by tswonke** [comment]
😉👍

**Comment by tswonke** [comment]
https://github.com/webfactor/laravel-generators/pull/9
